### ISSUE TITLE
한자 변환 키가 작동하지 않는 문제

### ISSUE THREAD

**Issue by ghost** [sokcuri/NaraeChat#14]
어떤 텍스트 필드에서도 한자 변환 키(RCtrl)가 작동하지 않는 것 같습니다
채팅, 게임 플레이에는 문제가 없겠지만 있는 기능이 작동하지 않아 이슈에 올렸습니다

혹시 아직 구현하지 않은 기능이라면 죄송합니다

감사합니다

**Comment by sokcuri** [comment]
현재 한자 변환 기능은 미구현 상태이지만 빠르게 구현해보도록 할게요

**Comment by ghost** [comment]
> 현재 한자 변환 기능은 미구현 상태이지만 빠르게 구현해보도록 할게요

그랬군요.. 감사합니다
천천히 진행하셔도 됩니다ㅎㅎ
