### ISSUE TITLE
1.16.2, 향후 상위 버전

### ISSUE THREAD

**Issue by ghost** [sokcuri/NaraeChat#17]
안녕하세요

버전이 올라갈 때마다 모드가 해당 버전을 지원하지 않아 여쭤봅니다

모드가 여러 게임 버전(예를 들면 1.16~1.16.3)을 지원할 수 있도록 할 수 있을까요?

혹시 불가능하다면 1.16.2 버전을 지원해주실 수 있으신가요?

향후 상위 버전에 대해선 지원 계획이 따로 없으신가요?

버전이 올라도 모드 소스 코드는 크게 바뀌지 않는 것 같아서 불편하실 것 같아요
게임 소스를 건드려야 하는건가..
의문이네용

이상입니다
이 시국에 코로나 조심하시고 건강하세요 ~

**Comment by sokcuri** [comment]
안녕하세요. 하는 일이 많아져서 나래챗은 잠시 유지보수 업무를 놓고 있습니다. 양해 부탁드립니다.

**Comment by MPThLee** [comment]
안녕하세요. 1.16.2는 아니지만 1.16.3 빌드를 만들었습니다. (#18) https://github.com/MPThLee/NaraeChat/releases/tag/1.16.3-0.7.1 
일단 간단하게 테스트를 돌려본 결과 문제는 없었습니다만, 기본적인 지원만 해둔거라 호환되지 않는 부분에 의해 문제가 발생할 수 있습니다.

**Comment by sokcuri** [comment]
안녕하세요. 상세하게 PR 및 기여해 주신 점 진심으로 감사합니다. 빠른시간 내 PR 코드 리뷰를 진행하도록 하겠습니다.

**Comment by ghost** [comment]
> 안녕하세요. 상세하게 PR 및 기여해 주신 점 진심으로 감사합니다. 빠른시간 내 PR 코드 리뷰를 진행하도록 하겠습니다.

와 두분 다 감사합니다
저도 버전업해서 빌드해보려 했다만 메서드 몇개가 오류나서 못했는데 어떻게 하신건지ㄷ
소쿠릿님도 바쁘실텐데 천천히 하시고 힘내세요 ㅎ

**Comment by MPThLee** [comment]
조금 더 분석해봤는데, `getHeight` 메소드 관련 문제만 해결되면 이번 버전은 1.16.x에선 전부 돌아갈 수 있는걸로 보입니다. 각 버전의 변경점이 크지 않아서 가능한것 같습니다.

추가: 생각과 달리 관련 코드 변경이 없어서 가능합니다.
https://github.com/MPThLee/NaraeChat/releases/tag/1.16.3-0.7.1+build2

**Comment by sokcuri** [comment]
확인 완료했습니다. 오후에 다시 코멘트 드리겠습니다

**Comment by sokcuri** [comment]
안녕하세요. 현재 현생이 너무 바빠져서 코드 리뷰를 하지 못하고 있습니다. 이 점 사과드리며 양해 부탁드립니다. 짬을 내어 업데이트나 이것저것 신경쓸 수 있도록 하겠습니다.

**Comment by Gplanet710** [comment]
> 안녕하세요. 현재 현생이 너무 바빠져서 코드 리뷰를 하지 못하고 있습니다. 이 점 사과드리며 양해 부탁드립니다. 짬을 내어 업데이트나 이것저것 신경쓸 수 있도록 하겠습니다.

일단 무리하지 말고 쉬십쇼
글 적을 시간도 없으신것 같은데..
