### ISSUE TITLE
마인크래프트 1.15 버전 지원

### ISSUE THREAD

**Issue by BasixKOR** [sokcuri/NaraeChat#5]
Minecraft Forge 1.15(.1)이 나왔는데 지원 계획이 있으신가 궁금합니다.

**Comment by soshimee** [comment]
패브릭 모드 아닌가요?

**Comment by BasixKOR** [comment]
@soshimee Forge 모드입니다.

**Comment by sokcuri** [comment]
안녕하세요. 1.15 버전에 대한 지원을 위한 빌드 작업을 이번주 진행할 예정입니다. 감사합니다

**Comment by sokcuri** [comment]
나래챗 1.16.1 모드 작업을 완료했으며 다운로드가 가능합니다. 감사합니다.
https://github.com/sokcuri/NaraeChat/releases/tag/1.16.1-0.7.0

**Comment by sokcuri** [comment]
1.15 버전도 지원해야 하나요?
