### ISSUE TITLE
1.15.2 버전과 향후 상위 버전

### ISSUE THREAD

**Issue by ghost** [sokcuri/NaraeChat#6]
1.15.2 버전에 대해 지원 계획 있으신가요?

**Comment by soshimee** [comment]
저도 그게 궁금하네요... 아직까지 아무말이 없으니..

**Comment by ghost** [comment]
트위터 봐서는 활동은 하고계신데 팔로우를 안받으시네요

이런 좋은 개발자가 제작을 안하시니 아쉽네요

**Comment by sokcuri** [comment]
안녕하세요. 늦게 확인한 점 양해의 말씀을 드립니다 ㅠㅠ 1.15.2 버전에 대한 지원 계획은 없지만 어려울것 같지는 않네요. 시간을 내서 주말에 작업해 보겠습니다

**Comment by ghost** [comment]
> 안녕하세요. 늦게 확인한 점 양해의 말씀을 드립니다 ㅠㅠ 1.15.2 버전에 대한 지원 계획은 없지만 어려울것 같지는 않네요. 시간을 내서 주말에 작업해 보겠습니다

우와 답변 감사합니다
혹시 못보고 계시나 걱정했는데 다행이네요ㅎㅎ

**Comment by soshimee** [comment]
곧 1.15.2가 나오겠네요 ㅎㅎ

**Comment by ghost** [comment]
안녕하세요 질문 작성자입니다.
현재 개발을 진행중이신 것 같은데 버그나 오류가 있으신지 아니면 시간이 맞지 않으셔서 출시가 어려우신건지 소식이 없으셔서 궁금하고 걱정됩니다.
혹시 바쁘신데 방해되진 않을까 우려됩니다만 개발자님의 현황을 알고싶습니다.
보셨는데 답장이 어려우시다면 이모티콘 하나라도 부탁드려요
감사합니다.

**Comment by sokcuri** [comment]
안녕하세요. 아무래도 남는시간 쪼개서 하다보니 일정이 조금 딜레이되는 경우가 있습니다. 기술검토만 진행했고 1.15.2 버전 진행상황은 덧붙여 올리도록 할게요

**Comment by sokcuri** [comment]
생각보다 많이 딜레이되고 있는점 사과드리구요. 기존에 잡혀있던 개발 일정이나 인터셉트가 많네요 ㅠㅠ

**Comment by ghost** [comment]
> 생각보다 많이 딜레이되고 있는점 사과드리구요. 기존에 잡혀있던 개발 일정이나 인터셉트가 많네요 ㅠㅠ

에이 아닙니다
개발자가 안바쁠수 있나요ㅎㅎ

이슈페이지에 버그리포트 몇개 올렸습니다!
작업이 빠르면 이렇게 오류가 많아질수도 있을텐테 조금 늦더라도 그런건 잡아야 하잖아요

**Comment by ghost** [comment]
오늘 1.16이 출시됐는데 지원하는 포지 나오면 혹시 지원하실 생각 있나요?

**Comment by sokcuri** [comment]
오래 기다리셨습니다. 1.16.1 버전 (1.16 하위 지원) 나래챗을 공개하였습니다
https://github.com/sokcuri/NaraeChat/releases/tag/1.16.1-0.7.0

**Comment by sokcuri** [comment]
여러가지 보조 기능들이 들어가 개발 속도가 엄청 더디게 되어 현재는 다른 부가기능을 제외하고 출시한 점 양해 부탁드려요

**Comment by ghost** [comment]
> 여러가지 보조 기능들이 들어가 개발 속도가 엄청 더디게 되어 현재는 다른 부가기능을 제외하고 출시한 점 양해 부탁드려요 

정말 감사합니다! 힘드셨을텐데 결국 만들어 내주셨네요
개발자는 역시 대단합니다
편리한 한글채팅 모드를 만들어 주셔서 감사합니다ㅎㅎ
