### ISSUE TITLE
1.14.4 버전에 버그가 있습니다

### ISSUE THREAD

**Issue by ghost** [sokcuri/NaraeChat#9]
안녕하세요
이전 버전에 나래챗 모드만 넣고 시험삼아 해보던 도중에 문제가 있는 것 같아 글 남깁니다

책과깃펜 아이템에 글을 쓸때 한영키가 먹히지 않는 현상이 있습니다
아무리 한영키를 눌러도 영문만 써집니다

버그인지는 모르겠지만 모루에서 한글로 아이템 이름을 수정하면 화살표에 X 표시가 생기면서 생성물이 나타나지 않거나 마지막 글자만 표시됩니다
이름 수정칸을 마우스 커서로 클릭하면 해결되긴 합니다만 살짝 불편한 감이 있습니다

폰트 설정에서 새로 설치한 글꼴이 선택창에 나와있지 않습니다

1.15.2 버전의 모드에서는 문제를 개선해주시길 바랍니다
편리한 한글채팅 모드를 개발해주셔서 감사합니다

**Comment by Gplanet710** [comment]
> 안녕하세요
> 이전 버전에 나래챗 모드만 넣고 시험삼아 해보던 도중에 문제가 있는 것 같아 글 남깁니다
> 
> 책과깃펜 아이템에 글을 쓸때 한영키가 먹히지 않는 현상이 있습니다
> 아무리 한영키를 눌러도 영문만 써집니다
> 
> 버그인지는 모르겠지만 모루에서 한글로 아이템 이름을 수정하면 화살표에 X 표시가 생기면서 생성물이 나타나지 않습니다
> 이름 수정칸을 마우스 커서로 클릭하면 해결되긴 합니다만 살짝 불편한 감이 있습니다
> 
> 폰트 설정에서 새로 설치한 글꼴이 선택창에 나와있지 않습니다
> 
> 1.15.2 버전의 모드에서는 문제를 개선해주시길 바랍니다
> 편리한 한글채팅 모드를 개발해주셔서 감사합니다
